// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kigzfqzvipxgakjlvbvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZ3pmcXp2aXB4Z2Framx2YnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTA5ODMsImV4cCI6MjA2OTc2Njk4M30.--fGkw3n5X4RTs45uzGBaxqOsN2GTCgkkciOJYXBN_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});